### ISSUE TITLE
$cpu is undefined

### ISSUE THREAD

**Issue by hesco** [AlliumCepa/webgui#32]
root@webgui:/opt/local/webgui/installer# perl webgui_installer.pl \
        --unattended \
        --domain-name webgui.example.com

Use of uninitialized value $cpu in concatenation (.) or string at webgui_installer.pl line 526.
Doing so may help get bugs fixed and problems worked around in future versions.
useradd --password secret --shell /bin/bash root:  
useradd: user 'root' already exists

Exit code 9 indicates failure.

OS: debian
perl: /usr/bin/perl

root: 1

cpu: 

If this is a bug, Scott should soon post a fix on http://twitter.com/scrottie, or please feel free to email scott@slowass.net to request updates.

---

```
    $ os = $^O;

    if( ! grep $os, qw/darwin linux/ ) {
        die "Sorry, your operating system is not yet supported by this installer.\nIt has no idea which packages need to be installed for target ``$os''.\nPlease look for the link to the source install method from the README.md.\n";
    }

    $os = 'debian' if $os eq 'linux' and -f '/etc/debian_version';
    $os = 'redhat' if $os eq 'linux' and -f '/etc/redhat-release';

    # only applicable to Linux

    if( $os eq 'linux' ) {
        $sixtyfour = $Config{archname} =~ m/x86_64/ ? '64' : ''; # XXX use these everywhere apt-get gets run
        $thirtytwo = $Config{archname} =~ m/i686/ ? '32' : '';

        $cpu = $Config{archname};
        $cpu =~ s{-.*}{};
        $cpu = 'i686' if $cpu eq 'i386'; # at least for RedHat
    }

```

As $os here is 'debian', we never reach the code which defines $cpu.

**Comment by scrottie** [comment]
Thanks for the report.

I should also add logic to catch when people try to create a 'root' user (which will essentially never work) and force them to pick again, unless I'm misunderstanding what's happening here.

**Comment by hesco** [comment]
I moved the $os = 'debian'|'redhat' lines past the block which defines $cpu and got stuck on another error, where I was unable to uncover root cause.  After some head scratching I finally abandoned my attempts at the unattended installation for the ncurses attended install.  

I had to manually install the experimental.pm module and restart the attended install three or four times to get to the end.  It finally hung on the chkconfig step w/o resolving itself.  But by opening another cli, I was able to run `/etc/init.d/webgui start` and use the browser interface to take the next step.  First installation of WebGUI for me.  

I'm still poking about trying to see where to take this.  I have a drupal site in desperate need of migration and a one week window to pull this off.  Interested to see if I can get this handled.  

Is this code too unstable to put a production site on?  Seeing 4500+ commits since the last tag (v7.8.0-4565-gebb3356) scares me.  Any reason you have not been tagging your work since the fork from upstream?

**Comment by scrottie** [comment]
wG7 is still considered the stable branch, and there's a "PlebGUI" branch of it that includes the Plack code but otherwise tracks 7.  That could be a good choice for production.

The important parts of wG8 are usable (both admin and site features).  A lot the more obscure stuff hasn't been heavily tested.  If you had been using 7 and were using a lot of it's features, I'd encourage you to stay with it and not risk breaking things in an upgrade, but if you're coming in new, I'd go with 8.

The installer is new and very much experimental, and I'm behind on bug fixes for it.  Sorry about that.  I'm hoping to catch up on those tomorrow.

8 is alphaware right now, especially the installer and parts of the admin.  The core inherited from 7 had the benefit of comprehensive unit tests so we know it's in pretty good shape.  7 gets released often, and it gets tagged when it gets released.  8 hasn't officially been released yet.  I'm working towards a beta release, and that will be tagged for sure.

The 8 development process has been a long road.  It started off way too ambitious and then got more and more stuff piled on.  (Sorry, Doug.)  4500+ commits should scare you.  Damage control on all of the bugs introduced there is a big project.

Mobile has changed a lot since that mobile theme was created.  Thankfully, creating new themes for wG is pretty straight forward.  Modernizing it (again; some of the themes have been modernized several times) is on the todo list.  I guess it will probably be Bootstrap now.  For the time being, you could potentially tweak the CSS of the mobile theme and fix some of the worst of it.

Part of what the installer tries to do is set up nginx and all of that, and that's not critical to just testing and playing with wG.  It should maybe ask if you even want that, especially since it's part of the OS that changes a lot and is therefore problematic.

**Comment by scrottie** [comment]
I'm not clear why $cpu is undefined.  My reading of the code path is that it should be set.  Around line 182, it figures out it's on Linux, then tries to extract the CPU info.

Could you please run this command and tell me what the output is?

     perl -e 'use Config; print $Config{archname};'

Thanks

**Comment by scrottie** [comment]
```
Creating database user.
 apt-get install -y perlmagick libssl-dev libexpat1-dev git curl nginx:
Reading package lists...
Building dependency tree...
Reading state information...
git is already the newest version.
libexpat1-dev is already the newest version.
nginx is already the newest version.
perlmagick is already the newest version.
curl is already the newest version.
libssl-dev is already the newest version.
The following packages were automatically installed and are no longer required:
  antlr3 firebird2.5-common firebird2.5-common-doc firmware-mod-kit junit4-doc
  libanydata-perl libarmadillo3 libavformat-dev libbeansbinding-java
  libbetter-appframework-java libbindex-java libbytelist-java libc3p0-java
  libcf0 libclass-accessor-grouped-perl libclass-dbi-abstractsearch-perl
  libclass-dbi-perl libclass-trigger-perl libclass-xsaccessor-perl
  libcommons-net1-java libcrypt-mcrypt-perl libcrypt-passwdmd5-perl libdap11
  libdapclient3 libdapserver7 libdbd-anydata-perl libdbix-contextualfetch-perl
  libemma-java libepsilon0 libfbclient2 libfelix-framework-java
  libfelix-main-java libflute-java libfreemarker-java
  libgetopt-lon
```
How the heck did that happen?  That's not an error.  $? is 0 for me after apt-get install <something already installed and current>

**Comment by scrottie** [comment]
Couldn't create /data/domains/localhost/webui: No such file or directory

Just pasting some more of these automatic reports in to here.  Sorry for the spam.

Ah.  I was wondering where all of those "useradd: user 'root' already exists" failures were coming from.  I thought for sure whoever was doing that would figure out they couldn't create root.  I forgot about unattended mode.  It's probably doing the same thing in "as few questions as possible" mode and I didn't notice because the "webgui" user got created once then it kept reusing it.

**Comment by scrottie** [comment]
Installer is now deprecated in favor of either a Docker image or the manual source install process.  I've removed it from the repo.  Work on wG8 helped get rid of annoying problems people had to deal with in getting things going on OSX for example so the source install is less problematic than it was once was.  Removing Perl module deps that that aren't portable or frequently fail is an ongoing chore.  Closing this as Will Not Fix.
